version: '3'
services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    volumes:
      - static:/static:rw
    environment:
      DJANGO_MODE: production
  db:
    image: "postgres:latest"
    volumes:
      - db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: project
      POSTGRES_PASSWORD: secret
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    ports:
      - "8080:80"
    volumes:
      - static:/static:ro
  vue:
    build:
      context: .
      dockerfile: vue.Dockerfile
    ports:
      - "8000:80"
    volumes:
      - static:/static:ro

volumes:
  static:
  db:
