version: '3'
services:
  db:
    image: "postgres"
    environment:
      - POSTGRES_DB=project
      - POSTGRES_USER=project
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    volumes:
      - .:/code
    depends_on:
      - db
    ports:
      - "8080:8080"
    # environment:
    #   DJANGO_MODE: production


volumes:
  postgres_data:
